# Generated by Django 4.2.19 on 2025-02-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_healthmetric_summary_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthmetric",
            name="health_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_metrics",
                to="main.healthdatafile",
            ),
        ),
        migrations.CreateModel(
            name="LLMAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=2500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "health_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_metrics",
                        to="main.healthdatafile",
                    ),
                ),
            ],
        ),
    ]
