name: Run Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SECRET_KEY
        run: echo "SECRET_KEY='test_secret_key'" >> $GITHUB_ENV

      - name: migrate
        run: |
          python manage.py makemigrations --check
          python manage.py migrate --noinput

      - name: test
        run: python manage.py test --verbosity=2
